### ISSUE TITLE
calcul du nombre de cas confiné

### ISSUE THREAD

**Issue by DydyFALL** [dofbi/covid19#1]
Bonjour Monsieur Diagne,
Permettez-moi de vous remercier d'abord pour cette formation très utile,
j'arrive pas à avoir le mème nombre de cas confiné, j'avoue que j'ai pas creusé, En attendant de trouver la solution à mon niveau ci- joint la capture.
Voir l'échelle aussi
N.B. Dans le fichier.csv j'ai rajouté evacue : date,cas,contact,importe,communautaire,total,gueri,mort,evacue

![image](https://user-images.githubusercontent.com/63017824/78248154-a26e0300-74db-11ea-88a3-8e5bf2728eed.png)
voilà merci encore
Khady FALL

**Comment by dofbi** [comment]
1. Une erreur dans les calculs et avec l'ajout des malades évacués, il a fallu apporter une amélioration dans le code. Je vous invite à récupérer la nouvelle version du tableau bord en tapent la commande suivante dans l'emplacement de votre projet

```
git pull
```

2. Pour graphe qui risque d'atteindre le maximum, allez dans la partie administration de votre Tableau de bord et chercher "Cas actuellement hospitalisés"

![Capture du 2020-04-02 22-31-19](https://user-images.githubusercontent.com/84446/78305946-b5132700-7531-11ea-9a91-d4d00a726f94.png)

Double cliquez dessus 

![Capture du 2020-04-02 22-32-16](https://user-images.githubusercontent.com/84446/78306149-310d6f00-7532-11ea-9188-d5e7cbee2866.png)

Changez la valeur de **"Max"**

Merci à vous pour votre intérêt

**Comment by DydyFALL** [comment]
Bonsoir
Bien reçu. Je vous remercie pour votre diligence diligence


Le jeu. 2 avr. 2020 à 22:38, Mamadou Diagne <notifications@github.com> a
écrit :
