### ISSUE TITLE
Déploiement

### ISSUE THREAD

**Issue by deoland** [dofbi/covid19#2]
Bonjour,
Merci du travail abbatu. Comment fait on à la fin pour déployer les fichiers sur un serveur Web. Ensuite pour le côté admin, est il possible d'avoir un mot de passe afin d'y avoir accès ?
Merci

**Comment by dofbi** [comment]
1. Je viens de mettre à jour le fichier README vous y trouvez des liens utiles pour déployer votre application en production.

Je vous propose de lire et choisir la plate-forme où vous êtes le plus familiariser

![Capture du 2020-04-02 22-43-52](https://user-images.githubusercontent.com/84446/78306656-72524e80-7533-11ea-8475-aace8adb40b7.png)

https://github.com/genova/covid19


2. Oui il vous possible d'avoir un mot de passe pour la partie d'administration.
Allez dans le fichier de configuration "settings.js"qui est dans le dossier ".node-red" et de commenter le lignes suivantes

```
adminAuth: {
       type: "credentials",
       users: [{
           username: "admin",
           password: "$2a$08$zZWtXTja0fB1pzD4sHCMyOCMYz2Z6dNbM6tl8sJogENOMcxWV9DN.",
           permissions: "*"
       }]
    },
```

Pour plus de détails sur la sécurisation de votre tableau de bord consultait le lien suivant

https://nodered.org/docs/user-guide/runtime/securing-node-red
