### ISSUE TITLE
Astuces serveur web supportant note Red pour accès à distance

### ISSUE THREAD

**Issue by babiraguel** [dofbi/covid19#3]
Bonjour Dofbi,

J'espère que tu vas bien. Merci pour le partage de ton code source et également pour la séance de coatching. En Mauritanie nous avons pu reprendre le code, le dashboard tourne bien en local. Nous voulons maintenant trouver un serveur web pour l'accès à distance et le déployer par la suite. 

Que pensez-vous de l'option Android? Que nous suggérez vous?

**Comment by dofbi** [comment]
Bonjour @babiraguel 
Et désolai pour la réponse tardive, j'ai update le fichier readme avec quelque recommandation le déployer votre application en production
https://github.com/genova/covid19/blob/master/README.md

J'ai pas de l’expérience pour Android je vous recommande heroku
